# This conda recipe is for use with the git repo (hence the local url).
# For a simple conda install (non bleeding-edge), see the conda-forge recipe at
# https://github.com/conda-forge/jupyter_nbextensions_configurator-feedstock

{% set version = '0.2.1' %}

package:
  name: jupyter_nbextensions_configurator
  version: {{ version }}

source:
  git_url: ../
  git_tag: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - jupyter_contrib_core >=0.2
    - jupyter_core
    - nbconvert
    - notebook >=4.0
    - pyyaml
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
    - jupyter_nbextensions_configurator.application

  commands:
    - jupyter nbextensions_configurator --help
    - jupyter nbextensions_configurator enable --help
    - jupyter nbextensions_configurator disable --help

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  home: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
